### ISSUE TITLE
Deploying Stack fails with MalformedPolicyDocumentError

### ISSUE THREAD

**Issue by OperatorJack** [bobbyhadz/aws-ses-send-emails#1]
Hello! I am following along with your article (great, by the way) and am attempting to deploy your example stack. However, I receive this error:

```
cdk-stack | 4/10 | 11:56:04 AM | CREATE_FAILED        | AWS::IAM::Policy               | mailer-function/ServiceRole/DefaultPolicy (mailerfunctionServiceRoleDefaultPolicy277D7D8B) 
The policy failed legacy parsing (Service: AmazonIdentityManagement; Status Code: 400; Error Code: MalformedPolicyDocument; Request ID: b955debc-6c6e-480c-9a05-267bfa6ace17; Proxy: null)
```

I simplfy cloned your repo, created the env file as instructed, then ran deploy. 

Any ideas what could be causing this?

Here is the full error message:

```
Failed resources:
cdk-stack | 11:56:04 AM | CREATE_FAILED        | AWS::IAM::Policy               | mailer-function/ServiceRole/DefaultPolicy (mailerfunctionServiceRoleDefaultPolicy277D7D8B) The policy failed legacy parsing (Service: AmazonIdentityManagement; Status Code: 400; Error Code: MalformedPolicyDocument; Request ID: b955debc-6c6e-480c-9a05-267bfa6ace17; Proxy: null) 
        new Policy (H:\GitHub\aws-ses-send-emails\node_modules\@aws-cdk\aws-iam\lib\policy.ts:89:22)
        \_ Role.addToPrincipalPolicy (H:\GitHub\aws-ses-send-emails\node_modules\@aws-cdk\aws-iam\lib\role.ts:236:28)
        \_ NodejsFunction.addToRolePolicy (H:\GitHub\aws-ses-send-emails\node_modules\@aws-cdk\aws-lambda\lib\function-base.ts:146:15)
        \_ new CdkStarterStack (H:\GitHub\aws-ses-send-emails\lib\cdk-starter-stack.ts:30:20)
        \_ Object.<anonymous> (H:\GitHub\aws-ses-send-emails\bin\cdk-starter.ts:6:1)      
        \_ Module._compile (node:internal/modules/cjs/loader:1103:14)
        \_ Module.m._compile (H:\GitHub\aws-ses-send-emails\node_modules\ts-node\src\index.ts:1056:23)
        \_ Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
        \_ Object.require.extensions.<computed> [as .ts] (H:\GitHub\aws-ses-send-emails\node_modules\ts-node\src\index.ts:1059:12)
        \_ Module.load (node:internal/modules/cjs/loader:981:32)
        \_ Function.Module._load (node:internal/modules/cjs/loader:822:12)
        \_ Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
        \_ main (H:\GitHub\aws-ses-send-emails\node_modules\ts-node\src\bin.ts:198:14)    
        \_ Object.<anonymous> (H:\GitHub\aws-ses-send-emails\node_modules\ts-node\src\bin.ts:288:3)
        \_ Module._compile (node:internal/modules/cjs/loader:1103:14)
        \_ Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)       
        \_ Module.load (node:internal/modules/cjs/loader:981:32)
        \_ Function.Module._load (node:internal/modules/cjs/loader:822:12)
        \_ Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
        \_ node:internal/main/run_main_module:17:47

 ❌  cdk-stack failed: Error: The stack named cdk-stack failed creation, it may need to beole: ROLLBACK_COMPLETE
    at Object.waitForStackDeploy (H:\GitHub\aws-ses-send-emails\node_modules\aws-cdk\lib\api\util\cloudformation.ts:307:11)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at prepareAndExecuteChangeSet (H:\GitHub\aws-ses-send-emails\node_modules\aws-cdk\lib\api\deploy-stack.ts:351:26)
    at CdkToolkit.deploy (H:\GitHub\aws-ses-send-emails\node_modules\aws-cdk\lib\cdk-toolkit.ts:194:24)
    at initCommandLine (H:\GitHub\aws-ses-send-emails\node_modules\aws-cdk\bin\cdk.ts:267:9)
The stack named cdk-stack failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE
```

**Comment by bobbyhadz** [comment]
My best guess is that you either didn't create an `env.ts` file in the root directory of the project or one or more of the values are not getting resolved.
The `env.ts` file has to export the following variables.

```javascript
export const SES_REGION = 'YOUR_SES_REGION';
export const SES_EMAIL_TO = 'YOUR_SES_RECIPIENT_EMAIL';
export const SES_EMAIL_FROM = 'YOUR_SES_SENDER_EMAIL';
```

To my knowledge, your error message means that one or more of the 3 values above are not found

**Comment by OperatorJack** [comment]
I dug around a little more... turns out that in the env file, the region must be all lower cased letters. I had `US-EAST-1`, when it should be `us-east-1`. Everything works after making that change, although might be worth mentioning in the article. Great work!
